network:
  renderer: networkd
  ethernets:
    eth0:
      addresses: [192.168.1.33/24]
      gateway4: 192.168.1.1
      optional: true
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
  version: 2
